name: actions

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-elixir@v1.4.0
        with:
          otp-version: 22.2.6
          elixir-version: 1.10.1
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get --only test
      - run: mix test
  
  check_formatted:
    name: Check formatted
    runs-ons: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-elixir@v1.4.0
        with:
          otp-version: 22.2.6
          elixir-version: 1.10.1
      - run: mix format --check-formatted
      - run: mix credo --strict

  compile_without_warnings:
    name: Compile without warnings
    runs-ons: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-elixir@v1.4.0
        with:
          otp-version: 22.2.6
          elixir-version: 1.9.4
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get
      - name: Compile without warnings
        run: mix compile --warning-as-errors
